source 'http://rubygems.org'
gem 'rails'
gem 'mongoid'
gem 'bson_ext'
gem 'devise'
gem 'cancan'
gem 'jquery-rails'
gem 'passenger'
gem 'capistrano'
gem 'haml'
gem 'spork', '~> 0.9.0.rc'
gem 'geokit'
gem 'sanitize'
gem 'simple_form'
gem 'turbolinks'
group :development, :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec'
  gem 'rspec-rails'
	gem 'watchr'
  gem 'shoulda'
  gem 'factory_girl_rails'
	gem 'faker'
  gem 'autotest'
  gem 'launchy'
  gem 'faker'
  gem 'haml-rails'
	gem 'debugger'
end

group :assets do
  gem 'sass-rails' # if running rails 3.1 or greater
  gem 'compass-rails'
end
