development: &defaults
  sessions:
    default: &default_session
      database: C41_development
      hosts:
        - localhost
      options:
  options:
    allow_dynamic_fields: false
    preload_models: true
    raise_not_found_error: false

test:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: C41_test

production:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: C41_development
      username: bob
      password: cannascore420
    replica_set:
      hosts:
        - localhost:27017
        - localhost:27017
        - localhost:27017
      database: C41_development
      options:
        consistency: :eventual
        safe: true
    shard:
      hosts:
        - localhost:27017
      database: C41_development
    another:
      uri: mongodb://bob:cannascore420@localhost:27017,localhost:27017/C41_development
  options:
    allow_dynamic_fields: false
    identity_map_enabled: true
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    skip_version_check: false
    use_activesupport_time_zone: true
    use_utc: true
